
apiVersion: eksctl.io/v1alpha5

kind: ClusterConfig

metadata:
  name: capstone-cluster
  region: us-west-1

nodeGroups:
  - name: blue-group
    instanceType: t2.nano
    desiredCapacity: 2
  - name: green-group
    instanceType: t2.nano
    desiredCapacity: 2