apiVersion: eksctl.io/v1alpha5

kind: ClusterConfig

metadata:
  name: capstone
  region: us-west-1

nodeGroups:
- name: blue-group
  instanceType: t2.micro
  desiredCapacity: 2
- name: green-group
  instanceType: t2.micro
  desiredCapacity: 2
