apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-test
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: test.eks.slitcloud.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
