apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-test
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: test.eks.slitcloud.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
